apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: samba-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: samba-hostpath
  volumeName: samba-pv
