apiVersion: v1
kind: PersistentVolume
metadata:
  name: samba-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: samba-hostpath
  hostPath:
    path: /srv/samba-share
    type: DirectoryOrCreate
